stages:
  - deploy

deploy:
  stage: deploy
  when: always
  script:
    - export PATH="/home/flutter/flutter/bin:$PATH"
    - /home/flutter/iframe/update.sh
  tags:
    - flutter-build
  only:
    - main
