stages:
  - deploy

deploy_dev_manual: &deploy_dev
  stage: deploy
  when: manual
  script:
    - /home/flutter/iframe/update.sh
  tags:
    - flutter build
  only:
    - main

deploy_dev_trigger:
  <<: *deploy_dev
  when: always
  only:
    - triggers