stages:
  - deploy

deploy:
  stage: deploy
  when: always
  script:
    - export PATH="/home/gitlab-runner/flutter/bin:$PATH"
    - /home/gitlab-runner/iframe/update.sh
  tags:
    - flutter-build
  only:
    - main
